name: Docker Image CI - Branch

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set Docker image tag
        id: vars
        run: |
          GIT_COMMIT=$(git rev-parse --short HEAD)
          echo "GIT_COMMIT=$GIT_COMMIT" >> $GITHUB_OUTPUT
          
          echo "TAG=cutting-edge" >> $GITHUB_OUTPUT
          echo "VERSION=0.0.0-dev-$GIT_COMMIT" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Repliqate/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/repliqate:${{ steps.vars.outputs.TAG }}
          build-args: |
            VERSION=${{ steps.vars.outputs.VERSION }}
            GIT_COMMIT=${{ steps.vars.outputs.GIT_COMMIT }}

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/repliqate
          readme-filepath: DOCKERHUB.md
          short-description: Modular, container-safe backup solution