name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set Docker image tag
        id: vars
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "release" ]]; then
            echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
            echo "TAG=manual" >> $GITHUB_OUTPUT
          else
            echo "TAG=latest" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Repliqate
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/repliqate:${{ steps.vars.outputs.TAG }}
