name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set Docker image tag
        id: vars
        run: |
          GIT_COMMIT=$(git rev-parse --short HEAD)
          echo "GIT_COMMIT=$GIT_COMMIT" >> $GITHUB_OUTPUT
          
          if [[ "${GITHUB_EVENT_NAME}" == "release" ]]; then
            # Strip 'v' prefix from version if present
            VERSION=${GITHUB_REF_NAME#v}
            echo "TAG=${GITHUB_REF_NAME},latest" >> $GITHUB_OUTPUT
            echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
            echo "TAG=manual" >> $GITHUB_OUTPUT
            echo "VERSION=0.0.0-manual-$GIT_COMMIT" >> $GITHUB_OUTPUT
          else
            echo "TAG=cutting-edge" >> $GITHUB_OUTPUT
            echo "VERSION=0.0.0-dev-$GIT_COMMIT" >> $GITHUB_OUTPUT
          fi


      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Repliqate/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/repliqate:${{ steps.vars.outputs.TAG }}
          build-args: |
            VERSION=${{ steps.vars.outputs.VERSION }}
            GIT_COMMIT=${{ steps.vars.outputs.GIT_COMMIT }}

